#
# Good and useful
# https://techcommunity.microsoft.com/t5/windows-dev-appconsult/first-steps-with-docker-and-kubernetes-introduction/ba-p/357525
#
# Note: This is the yaml file to start a set of containers in docker-desktop embeded k8s.
#
# To run:
# $ docker stack deploy --compose-file ./local-k8s.yaml myapp
#
# To stop:
# $ docker stack rm myapp
#
# To enable 49172 port for mssql, please look at "Configure SQL Server to listen on a specific port"
# https://www.teamdotnetnuke.com/index.php?/Knowledgebase/Article/View/218/20/configure-sql-server-to-listen-on-a-specific-port
#
# To enable firewall, in windows firewall -> add inbound rules
# 1. Enable port 90 - for gqlapi visit localhost ip/port of odataapi
# 2. Enable port 49172 - for odataapi visit localhost mssql
#
# To test:
# 1. visit http://localhost:90/Readme and http://localhost:90/OData/AllanNotice to verify the odata api works
# 2. visit http://localhost:92/graphql
# 3. input following to verify gqlapi works,
# mutation {
#   heartbeatadd(uri: "http://host.docker.internal:90/OData/AllanNotice"){
#     id,
#     name,
#     desc
#   }
# }
#

version: '3'
services:
  gqlapi:
    image: gqlapi-local:v1.0
    ports:
      - "92:8000"
  odata-api2:
    image: odataapi-dev:v1.0
    ports:
      - "90:80"

